import type { Metadata } from "next";
import { fontInter } from "@/styles/fonts";
import "@/styles/globals.css";
import { CartProvider } from "@/context/cart-context";
import FrontNavbar from "@/components/front/navbar";
import FrontAnnouncement from "@/components/front/announcement";

export const metadata: Metadata = {
  title: {
    template: '%s | UrbanElegance',
    default: 'UrbanElegance',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontInter.className} antialiased`}>
        <CartProvider>
          <FrontAnnouncement />
          <FrontNavbar />
          <main>{children}</main>
        </CartProvider>
      </body>
    </html>
  );
}
